spring:
#redis配置
  redis:
    host: localhost
    port: 8081
  #mysql
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/studio_sigh_up_db
file:
  uploadPath: E:/repository